-- Seeding exercise table
INSERT INTO exercises (name, muscle_group, subcategory)
SELECT t.name, t.muscle_group, t.subcategory
FROM (
  VALUES
    ('Ab Scissors', 'Abdomen', NULL),
    ('Ab Wheel', 'Abdomen', NULL),
    ('Bicycle Crunch', 'Abdomen', NULL),
    ('Bicycle Crunch Raised Legs', 'Abdomen', NULL),
    ('Cable Core Palloff Press', 'Abdomen', NULL),
    ('Cable Crunch', 'Abdomen', NULL),
    ('Cable Twist (Down to up)', 'Abdomen', NULL),
    ('Cable Twist (Up to down)', 'Abdomen', NULL),
    ('Crunch', 'Abdomen', NULL),
    ('Crunch (Machine)', 'Abdomen', NULL),
    ('Crunch (Weighted)', 'Abdomen', NULL),
    ('Dead Bug', 'Abdomen', NULL),
    ('Decline Crunch', 'Abdomen', NULL),
    ('Decline Crunch (Weighted)', 'Abdomen', NULL),
    ('Dragon Flag', 'Abdomen', NULL),
    ('Dragonfly', 'Abdomen', NULL),
    ('Elbow to Knee', 'Abdomen', NULL),
    ('Flutter Kicks', 'Abdomen', NULL),
    ('Hanging Knee Raise', 'Abdomen', NULL),
    ('Hanging Leg Raise', 'Abdomen', NULL),
    ('Heel Taps', 'Abdomen', NULL),
    ('Hollow Rock', 'Abdomen', NULL),
    ('Jack Knife (Suspension)', 'Abdomen', NULL),
    ('Jackknife Sit Up', 'Abdomen', NULL),
    ('Knee Raise Parallel Bars', 'Abdomen', NULL),
    ('L-Sit Hold', 'Abdomen', NULL),
    ('Landmine 180', 'Abdomen', NULL),
    ('Leg Raise Parallel Bars', 'Abdomen', NULL),
    ('Lying Knee Raise', 'Abdomen', NULL),
    ('Lying Leg Raise', 'Abdomen', NULL),
    ('Oblique Crunch', 'Abdomen', NULL),
    ('Plank', 'Abdomen', NULL),
    ('Reverse Crunch', 'Abdomen', NULL),
    ('Reverse Plank', 'Abdomen', NULL),
    ('Russian Twist (Bodyweight)', 'Abdomen', NULL),
    ('Russian Twist (Weighted)', 'Abdomen', NULL),
    ('Side Bend', 'Abdomen', NULL),
    ('Side Bend (Dumbbell)', 'Abdomen', NULL),
    ('Side Plank', 'Abdomen', NULL),
    ('Sit Up', 'Abdomen', NULL),
    ('Sit Up (Weighted)', 'Abdomen', NULL),
    ('Spiderman', 'Abdomen', NULL),
    ('Toe Touch', 'Abdomen', NULL),
    ('Toes to Bar', 'Abdomen', NULL),
    ('Torso Rotation', 'Abdomen', NULL),
    ('V Up', 'Abdomen', NULL),
    ('Hip Abduction (Machine)', 'Pierna', NULL),
    ('Hip Adduction (Machine)', 'Pierna', NULL),
    ('21s Bicep Curl', 'Brazo', 'Bíceps'),
    ('Behind the Back Curl (Cable)', 'Brazo', 'Bíceps'),
    ('Bicep Curl (Barbell)', 'Brazo', 'Bíceps'),
    ('Bicep Curl (Cable)', 'Brazo', 'Bíceps'),
    ('Bicep Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Bicep Curl (Machine)', 'Brazo', 'Bíceps'),
    ('Bicep Curl (Suspension)', 'Brazo', 'Bíceps'),
    ('Concentration Curl', 'Brazo', 'Bíceps'),
    ('Cross Body Hammer Curl', 'Brazo', 'Bíceps'),
    ('Drag Curl', 'Brazo', 'Bíceps'),
    ('EZ Bar Biceps Curl', 'Brazo', 'Bíceps'),
    ('Hammer Curl (Band)', 'Brazo', 'Bíceps'),
    ('Hammer Curl (Cable)', 'Brazo', 'Bíceps'),
    ('Hammer Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Kettlebell Curl', 'Brazo', 'Bíceps'),
    ('Overhead Curl (Cable)', 'Brazo', 'Bíceps'),
    ('Pinwheel Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Plate Curl', 'Brazo', 'Bíceps'),
    ('Preacher Curl (Barbell)', 'Brazo', 'Bíceps'),
    ('Preacher Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Preacher Curl (Machine)', 'Brazo', 'Bíceps'),
    ('Reverse Curl (Barbell)', 'Brazo', 'Bíceps'),
    ('Reverse Curl (Cable)', 'Brazo', 'Bíceps'),
    ('Reverse Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Reverse Grip Concentration Curl', 'Brazo', 'Bíceps'),
    ('Rope Cable Curl', 'Brazo', 'Bíceps'),
    ('Seated Incline Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Single Arm Curl (Cable)', 'Brazo', 'Bíceps'),
    ('Spider Curl (Barbell)', 'Brazo', 'Bíceps'),
    ('Spider Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Waiter Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Zottman Curl (Dumbbell)', 'Brazo', 'Bíceps'),
    ('Calf Extension (Machine)', 'Pierna', NULL),
    ('Calf Press (Machine)', 'Pierna', NULL),
    ('Seated Calf Raise', 'Pierna', NULL),
    ('Single Leg Standing Calf Raise', 'Pierna', NULL),
    ('Single Leg Standing Calf Raise (Barbell)', 'Pierna', NULL),
    ('Single Leg Standing Calf Raise (Dumbbell)', 'Pierna', NULL),
    ('Single Leg Standing Calf Raise (Machine)', 'Pierna', NULL),
    ('Standing Calf Raise', 'Pierna', NULL),
    ('Standing Calf Raise (Barbell)', 'Pierna', NULL),
    ('Standing Calf Raise (Dumbbell)', 'Pierna', NULL),
    ('Standing Calf Raise (Machine)', 'Pierna', NULL),
    ('Standing Calf Raise (Smith)', 'Pierna', NULL),
    ('Around The World', 'Pecho', NULL),
    ('Bench Press (Barbell)', 'Pecho', NULL),
    ('Bench Press (Cable)', 'Pecho', NULL),
    ('Bench Press (Dumbbell)', 'Pecho', NULL),
    ('Bench Press (Smith Machine)', 'Pecho', NULL),
    ('Bench Press - Wide Grip (Barbell)', 'Pecho', NULL),
    ('Butterfly (Pec Deck)', 'Pecho', NULL),
    ('Cable Fly Crossovers', 'Pecho', NULL),
    ('Chest Dip', 'Pecho', NULL),
    ('Chest Dip (Assisted)', 'Pecho', NULL),
    ('Chest Dip (Weighted)', 'Pecho', NULL),
    ('Chest Fly (Band)', 'Pecho', NULL),
    ('Chest Fly (Dumbbell)', 'Pecho', NULL),
    ('Chest Fly (Machine)', 'Pecho', NULL),
    ('Chest Fly (Suspension)', 'Pecho', NULL),
    ('Chest Press (Band)', 'Pecho', NULL),
    ('Chest Press (Machine)', 'Pecho', NULL),
    ('Clap Push Ups', 'Pecho', NULL),
    ('Decline Bench Press (Barbell)', 'Pecho', NULL),
    ('Decline Bench Press (Dumbbell)', 'Pecho', NULL),
    ('Decline Bench Press (Machine)', 'Pecho', NULL),
    ('Decline Bench Press (Smith Machine)', 'Pecho', NULL),
    ('Decline Chest Fly (Dumbbell)', 'Pecho', NULL),
    ('Decline Push Up', 'Pecho', NULL),
    ('Dumbbell Squeeze Press', 'Pecho', NULL),
    ('Feet Up Bench Press (Barbell)', 'Pecho', NULL),
    ('Floor Press (Barbell)', 'Pecho', NULL),
    ('Floor Press (Dumbbell)', 'Pecho', NULL),
    ('Hex Press (Dumbbell)', 'Pecho', NULL),
    ('Incline Bench Press (Barbell)', 'Pecho', NULL),
    ('Incline Bench Press (Dumbbell)', 'Pecho', NULL),
    ('Incline Bench Press (Smith Machine)', 'Pecho', NULL),
    ('Incline Chest Fly (Dumbbell)', 'Pecho', NULL),
    ('Incline Chest Press (Machine)', 'Pecho', NULL),
    ('Incline Push Ups', 'Pecho', NULL),
    ('Iso-Lateral Chest Press (Machine)', 'Pecho', NULL),
    ('Kneeling Push Up', 'Pecho', NULL),
    ('Low Cable Fly Crossovers', 'Pecho', NULL),
    ('One Arm Push Up', 'Pecho', NULL),
    ('Plank Pushup', 'Pecho', NULL),
    ('Plate Press', 'Pecho', NULL),
    ('Plate Squeeze (Svend Press)', 'Pecho', NULL),
    ('Push Up', 'Pecho', NULL),
    ('Push Up (Weighted)', 'Pecho', NULL),
    ('Push Up - Close Grip', 'Pecho', NULL),
    ('Ring Dips', 'Pecho', NULL),
    ('Ring Push Up', 'Pecho', NULL),
    ('Seated Chest Flys (Cable)', 'Pecho', NULL),
    ('Single Arm Cable Crossover', 'Pecho', NULL),
    ('Glutes', 'Glúteo', NULL),
    ('Behind the Back Bicep Wrist Curl (Barbell)', 'Brazo', 'Antebrazo'),
    ('Seated Palms Up Wrist Curl', 'Brazo', 'Antebrazo'),
    ('Seated Wrist Extension (Barbell)', 'Brazo', 'Antebrazo'),
    ('Wrist Roller', 'Brazo', 'Antebrazo'),
    ('Bird Dog', 'Pierna', NULL),
    ('Cable Pull Through', 'Glúteo', NULL),
    ('Clamshell', 'Glúteo', NULL),
    ('Deadlift (Band)', 'Glúteo', NULL),
    ('Deadlift (Barbell)', 'Glúteo', NULL),
    ('Deadlift (Dumbbell)', 'Glúteo', NULL),
    ('Deadlift (Smith Machine)', 'Glúteo', NULL),
    ('Deadlift (Trap bar)', 'Glúteo', NULL),
    ('Fire Hydrants', 'Glúteo', NULL),
    ('Frog Pumps (Dumbbell)', 'Glúteo', NULL),
    ('Glute Bridge', 'Glúteo', NULL),
    ('Glute Kickback (Machine)', 'Glúteo', NULL),
    ('Glute Kickback on Floor', 'Glúteo', NULL),
    ('Hip Thrust', 'Glúteo', NULL),
    ('Hip Thrust (Barbell)', 'Glúteo', NULL),
    ('Hip Thrust (Machine)', 'Glúteo', NULL),
    ('Hip Thrust (Smith Machine)', 'Glúteo', NULL),
    ('Lateral Band Walks', 'Glúteo', NULL),
    ('Lateral Leg Raises', 'Glúteo', NULL),
    ('Partial Glute Bridge (Barbell)', 'Glúteo', NULL),
    ('Rear Kick (Machine)', 'Glúteo', NULL),
    ('Reverse Hyperextension', 'Glúteo', NULL),
    ('Single Leg Glute Bridge', 'Glúteo', NULL),
    ('Single Leg Hip Thrust', 'Glúteo', NULL),
    ('Single Leg Hip Thrust (Dumbbell)', 'Glúteo', NULL),
    ('Standing Cable Glute Kickbacks', 'Glúteo', NULL),
    ('Sumo Deadlift', 'Glúteo', NULL),
    ('Glute Ham Raise', 'Pierna', NULL),
    ('Good Morning (Barbell)', 'Pierna', NULL),
    ('Lying Leg Curl (Machine)', 'Pierna', NULL),
    ('Nordic Hamstrings Curls', 'Pierna', NULL),
    ('Romanian Deadlift (Barbell)', 'Pierna', NULL),
    ('Romanian Deadlift (Dumbbell)', 'Pierna', NULL),
    ('Seated Leg Curl (Machine)', 'Pierna', NULL),
    ('Single Leg Romanian Deadlift (Barbell)', 'Pierna', NULL),
    ('Single Leg Romanian Deadlift (Dumbbell)', 'Pierna', NULL),
    ('Standing Leg Curls', 'Pierna', NULL),
    ('Straight Leg Deadlift', 'Pierna', NULL),
    ('Chin Up', 'Espalda', NULL),
    ('Chin Up (Assisted)', 'Espalda', NULL),
    ('Chin Up (Weighted)', 'Espalda', NULL),
    ('Dumbbell Row', 'Espalda', NULL),
    ('Iso-Lateral High Row (Machine)', 'Espalda', NULL),
    ('Kipping Pull Up', 'Espalda', NULL),
    ('Kneeling Pulldown (band)', 'Espalda', NULL),
    ('Lat Pulldown (Band)', 'Espalda', NULL),
    ('Lat Pulldown (Cable)', 'Espalda', NULL),
    ('Lat Pulldown (Machine)', 'Espalda', NULL),
    ('Lat Pulldown - Close Grip (Cable)', 'Espalda', NULL),
    ('Negative Pull Up', 'Espalda', NULL),
    ('Pull Up', 'Espalda', NULL),
    ('Pull Up (Assisted)', 'Espalda', NULL),
    ('Pull Up (Band)', 'Espalda', NULL),
    ('Pull Up (Weighted)', 'Espalda', NULL),
    ('Pullover (Dumbbell)', 'Espalda', NULL),
    ('Pullover (Machine)', 'Espalda', NULL),
    ('Reverse Grip Lat Pulldown (Cable)', 'Espalda', NULL),
    ('Ring Pull Up', 'Espalda', NULL),
    ('Rope Straight Arm Pulldown', 'Espalda', NULL),
    ('Single Arm Lat Pulldown', 'Espalda', NULL),
    ('Sternum Pull up (Gironda)', 'Espalda', NULL),
    ('Straight Arm Lat Pulldown (Cable)', 'Espalda', NULL),
    ('Vertical Traction (Machine)', 'Espalda', NULL),
    ('Wide Pull Up', 'Espalda', NULL),
    ('Back Extension (Hyperextension)', 'Espalda', NULL),
    ('Back Extension (Machine)', 'Espalda', NULL),
    ('Back Extension (Weighted Hyperextension)', 'Espalda', NULL),
    ('Superman', 'Espalda', NULL),
    ('Lying Neck Curls', 'Espalda', NULL),
    ('Lying Neck Curls (Weighted)', 'Espalda', NULL),
    ('Lying Neck Extension', 'Espalda', NULL),
    ('Lying Neck Extension (Weighted)', 'Espalda', NULL),
    ('Assisted Pistol Squats', 'Pierna', NULL),
    ('Belt Squat (Machine)', 'Pierna', NULL),
    ('Box Jump', 'Pierna', NULL),
    ('Box Squat (Barbell)', 'Pierna', NULL),
    ('Bulgarian Split Squat', 'Pierna', NULL),
    ('Curtsy Lunge (Dumbbell)', 'Pierna', NULL),
    ('Dumbbell Step Up', 'Pierna', NULL),
    ('Frog Jumps', 'Pierna', NULL),
    ('Front Squat', 'Pierna', NULL),
    ('Full Squat', 'Pierna', NULL),
    ('Goblet Squat', 'Pierna', NULL),
    ('Hack Squat', 'Pierna', NULL),
    ('Hack Squat (Machine)', 'Pierna', NULL),
    ('Jump Squat', 'Pierna', NULL),
    ('Jumping Lunge', 'Pierna', NULL),
    ('Kettlebell Goblet Squat', 'Pierna', NULL),
    ('Lateral Box Jump', 'Pierna', NULL),
    ('Lateral Lunge', 'Pierna', NULL),
    ('Lateral Squat', 'Pierna', NULL),
    ('Leg Extension (Machine)', 'Pierna', NULL),
    ('Leg Press (Machine)', 'Pierna', NULL),
    ('Leg Press Horizontal (Machine)', 'Pierna', NULL),
    ('Lunge', 'Pierna', NULL),
    ('Lunge (Barbell)', 'Pierna', NULL),
    ('Lunge (Dumbbell)', 'Pierna', NULL),
    ('Overhead Dumbbell Lunge', 'Pierna', NULL),
    ('Pause Squat (Barbell)', 'Pierna', NULL),
    ('Pendulum Squat (Machine)', 'Pierna', NULL),
    ('Pistol Squat', 'Pierna', NULL),
    ('Reverse Lunge', 'Pierna', NULL),
    ('Reverse Lunge (Barbell)', 'Pierna', NULL),
    ('Reverse Lunge (Dumbbell)', 'Pierna', NULL),
    ('Single Leg Extensions', 'Pierna', NULL),
    ('Single Leg Press (Machine)', 'Pierna', NULL),
    ('Sissy Squat (Weighted)', 'Pierna', NULL),
    ('Split Squat (Dumbbell)', 'Pierna', NULL),
    ('Squat (Band)', 'Pierna', NULL),
    ('Squat (Barbell)', 'Pierna', NULL),
    ('Squat (Bodyweight)', 'Pierna', NULL),
    ('Squat (Dumbbell)', 'Pierna', NULL),
    ('Squat (Machine)', 'Pierna', NULL),
    ('Squat (Smith Machine)', 'Pierna', NULL),
    ('Squat (Suspension)', 'Pierna', NULL),
    ('Step Up', 'Pierna', NULL),
    ('Sumo Squat', 'Pierna', NULL),
    ('Sumo Squat (Barbell)', 'Pierna', NULL),
    ('Sumo Squat (Dumbbell)', 'Pierna', NULL),
    ('Sumo Squat (Kettlebell)', 'Pierna', NULL),
    ('Walking Lunge', 'Pierna', NULL),
    ('Walking Lunge (Dumbbell)', 'Pierna', NULL),
    ('Wall Sit', 'Pierna', NULL),
    ('Zercher Squat', 'Pierna', NULL),
    ('Arnold Press (Dumbbell)', 'Brazo', 'Hombro'),
    ('Band Pullaparts', 'Brazo', 'Hombro'),
    ('Chest Supported Reverse Fly (Dumbbell)', 'Brazo', 'Hombro'),
    ('Chest Supported Y Raise (Dumbbell)', 'Brazo', 'Hombro'),
    ('Face Pull', 'Brazo', 'Hombro'),
    ('Front Raise (Band)', 'Brazo', 'Hombro'),
    ('Front Raise (Barbell)', 'Brazo', 'Hombro'),
    ('Front Raise (Cable)', 'Brazo', 'Hombro'),
    ('Front Raise (Dumbbell)', 'Brazo', 'Hombro'),
    ('Front Raise (Suspension)', 'Brazo', 'Hombro'),
    ('Handstand Push Up', 'Brazo', 'Hombro'),
    ('Kettlebell Around the World', 'Brazo', 'Hombro'),
    ('Kettlebell Halo', 'Brazo', 'Hombro'),
    ('Kettlebell Shoulder Press', 'Brazo', 'Hombro'),
    ('Lateral Raise (Band)', 'Brazo', 'Hombro'),
    ('Lateral Raise (Cable)', 'Brazo', 'Hombro'),
    ('Lateral Raise (Dumbbell)', 'Brazo', 'Hombro'),
    ('Lateral Raise (Machine)', 'Brazo', 'Hombro'),
    ('Overhead Plate Raise', 'Brazo', 'Hombro'),
    ('Overhead Press (Barbell)', 'Brazo', 'Hombro'),
    ('Overhead Press (Dumbbell)', 'Brazo', 'Hombro'),
    ('Overhead Press (Smith Machine)', 'Brazo', 'Hombro'),
    ('Pike Pushup', 'Brazo', 'Hombro'),
    ('Plate Front Raise', 'Brazo', 'Hombro'),
    ('Push Press', 'Brazo', 'Hombro'),
    ('Rear Delt Reverse Fly (Cable)', 'Brazo', 'Hombro'),
    ('Rear Delt Reverse Fly (Dumbbell)', 'Brazo', 'Hombro'),
    ('Rear Delt Reverse Fly (Machine)', 'Brazo', 'Hombro'),
    ('Reverse Fly Single Arm (Cable)', 'Brazo', 'Hombro'),
    ('Seated Lateral Raise (Dumbbell)', 'Brazo', 'Hombro'),
    ('Seated Overhead Press (Barbell)', 'Brazo', 'Hombro'),
    ('Seated Overhead Press (Dumbbell)', 'Brazo', 'Hombro'),
    ('Seated Shoulder Press (Machine)', 'Brazo', 'Hombro'),
    ('Shoulder Press (Dumbbell)', 'Brazo', 'Hombro'),
    ('Shoulder Press (Machine Plates)', 'Brazo', 'Hombro'),
    ('Shoulder Taps', 'Brazo', 'Hombro'),
    ('Single Arm Landmine Press (Barbell)', 'Brazo', 'Hombro'),
    ('Single Arm Lateral Raise (Cable)', 'Brazo', 'Hombro'),
    ('Standing Military Press (Barbell)', 'Brazo', 'Hombro'),
    ('Upright Row (Barbell)', 'Brazo', 'Hombro'),
    ('Upright Row (Cable)', 'Brazo', 'Hombro'),
    ('Upright Row (Dumbbell)', 'Brazo', 'Hombro'),
    ('Shrug (Barbell)', 'Espalda', NULL),
    ('Shrug (Cable)', 'Espalda', NULL),
    ('Shrug (Dumbbell)', 'Espalda', NULL),
    ('Shrug (Machine)', 'Espalda', NULL),
    ('Shrug (Smith Machine)', 'Espalda', NULL),
    ('Bench Dip', 'Brazo', 'Tríceps'),
    ('Bench Press - Close Grip (Barbell)', 'Brazo', 'Tríceps'),
    ('Diamond Push Up', 'Brazo', 'Tríceps'),
    ('Floor Triceps Dip', 'Brazo', 'Tríceps'),
    ('JM Press (Barbell)', 'Brazo', 'Tríceps'),
    ('Overhead Triceps Extension (Cable)', 'Brazo', 'Tríceps'),
    ('Seated Dip Machine', 'Brazo', 'Tríceps'),
    ('Seated Triceps Press', 'Brazo', 'Tríceps'),
    ('Single Arm Tricep Extension (Dumbbell)', 'Brazo', 'Tríceps'),
    ('Single Arm Triceps Pushdown (Cable)', 'Brazo', 'Tríceps'),
    ('Skullcrusher (Barbell)', 'Brazo', 'Tríceps'),
    ('Skullcrusher (Dumbbell)', 'Brazo', 'Tríceps'),
    ('Triceps Dip', 'Brazo', 'Tríceps'),
    ('Triceps Dip (Assisted)', 'Brazo', 'Tríceps'),
    ('Triceps Dip (Weighted)', 'Brazo', 'Tríceps'),
    ('Triceps Extension (Barbell)', 'Brazo', 'Tríceps'),
    ('Triceps Extension (Cable)', 'Brazo', 'Tríceps'),
    ('Triceps Extension (Dumbbell)', 'Brazo', 'Tríceps'),
    ('Triceps Extension (Machine)', 'Brazo', 'Tríceps'),
    ('Triceps Extension (Suspension)', 'Brazo', 'Tríceps'),
    ('Triceps Kickback (Cable)', 'Brazo', 'Tríceps'),
    ('Triceps Kickback (Dumbbell)', 'Brazo', 'Tríceps'),
    ('Triceps Pressdown', 'Brazo', 'Tríceps'),
    ('Triceps Pushdown', 'Brazo', 'Tríceps'),
    ('Triceps Rope Pushdown', 'Brazo', 'Tríceps'),
    ('Wide-Elbow Triceps Press (Dumbbell)', 'Brazo', 'Tríceps'),
    ('Bent Over Row (Band)', 'Espalda', NULL),
    ('Bent Over Row (Barbell)', 'Espalda', NULL),
    ('Bent Over Row (Dumbbell)', 'Espalda', NULL),
    ('Chest Supported Incline Row (Dumbbell)', 'Espalda', NULL),
    ('Dead Hang', 'Espalda', NULL),
    ('Gorilla Row (Kettlebell)', 'Espalda', NULL),
    ('Inverted Row', 'Espalda', NULL),
    ('Iso-Lateral Low Row', 'Espalda', NULL),
    ('Iso-Lateral Row (Machine)', 'Espalda', NULL),
    ('Landmine Row', 'Espalda', NULL),
    ('Low Row (Suspension)', 'Espalda', NULL),
    ('Meadows Rows (Barbell)', 'Espalda', NULL),
    ('Pendlay Row (Barbell)', 'Espalda', NULL),
    ('Rack Pull', 'Espalda', NULL),
    ('Renegade Row (Dumbbell)', 'Espalda', NULL),
    ('Scapular Pull Ups', 'Espalda', NULL),
    ('Seated Cable Row - Bar Grip', 'Espalda', NULL),
    ('Seated Cable Row - Bar Wide Grip', 'Espalda', NULL),
    ('Seated Cable Row - V Grip (Cable)', 'Espalda', NULL),
    ('Seated Row (Machine)', 'Espalda', NULL),
    ('Single Arm Cable Row', 'Espalda', NULL),
    ('T Bar Row', 'Espalda', NULL)
) AS t(name, muscle_group, subcategory)
WHERE NOT EXISTS (
  SELECT 1 FROM exercises WHERE exercises.name = t.name
);
